---
title: "Model"
author: "Jianyu"
date: "9/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sjPlot)
library(lme4)
library(lmerTest)
library(ggpubr)
set.seed(42)
```


```{r}
pcr_screen_salivaswab <- read.csv(file = "../data/pcr_screen_salivaswab_1.csv")
demo <- readRDS("../data/demohist_salivaswab_1.RDS")

#extract the real_onset from the "demo" dataset and join to the pcr_screen_salivaswab
demo <- demo %>% select(study_id, real_onset)
pcr_screen_salivaswab <- pcr_screen_salivaswab %>% 
  mutate(study_id=as.character(study_id)) %>% 
  left_join(demo, by="study_id")


#create a dataset containing only paired saliva and mt
MT <- pcr_screen_salivaswab %>% filter(sample_type == "Midturbinate Swab") %>% select(study_id, sample_date)
saliva <- pcr_screen_salivaswab %>% filter(sample_type == "Saliva") %>% select(study_id, sample_date)
MT_SALIVA <- left_join(intersect(MT, saliva), pcr_screen_salivaswab, by=c("study_id","sample_date"))  %>% filter(sample_type %in% c("Saliva","Midturbinate Swab"))

#create "pos" variable indicating positivity
ctscreencols <- c("ct_ngene_screen","ct_sgene_screen","ct_orf1ab_screen")
MT_SALIVA$pos <- MT_SALIVA[,ctscreencols] %>% apply(c(1,2),function(x) {x<40}) %>% apply(1,function(x) {sum(x)>=2})

MT_SALIVA <- MT_SALIVA %>% 
  mutate(positivity = as.numeric(if_else(pos==TRUE, 1, 0)))

#create a list of people who became positive by either test
positive_list <- MT_SALIVA %>% 
  filter(pos == TRUE) %>% 
  select(study_id) %>% 
  unique()
nrow(positive_list)

#subset the MT_SALIVA dataset to only those became positive later
MT_SALIVA_POSITIVE <- MT_SALIVA %>% 
  right_join(positive_list)

length(unique(MT_SALIVA_POSITIVE$study_id))

MT_SALIVA_POSITIVE <- MT_SALIVA_POSITIVE %>% mutate(days_since_symptom_onset = sample_date- as.numeric(real_onset))

#remove "413" because of no symptom
MT_SALIVA_POSITIVE_sub <- MT_SALIVA_POSITIVE %>% 
  filter(study_id != "413")
length(unique(MT_SALIVA_POSITIVE_sub$study_id))
length(unique(MT_SALIVA_POSITIVE_sub$sample_id))

```

```{r}
#model the effect of saliva on positivity for different periods
table3 <- function(day1, day2){
  MT_SALIVA_POSITIVE_sub <- MT_SALIVA_POSITIVE_sub %>% 
  mutate(period_day = if_else(days_since_symptom_onset>=day1 & days_since_symptom_onset<=day2, 1, 0))
  sub_day <- MT_SALIVA_POSITIVE_sub %>% 
  filter(period_day==1)

#test the association between sample type and positivity
model_day <- glm( positivity ~ sample_type, data = sub_day, family = "binomial")
summary(model_day)
note <- paste(day1,"to",day2)

saliva <- sub_day %>% filter(sample_type == "Saliva")
mts <- sub_day %>% filter(sample_type == "Midturbinate Swab")
pos_saliva <- nrow(saliva %>% filter(positivity == 1))
total_saliva <- nrow(saliva)
pos_mts <- nrow(mts %>% filter(positivity == 1))
total_mts <- nrow(mts)
note_saliva <- gsub(" ","",paste(pos_saliva, "/", total_saliva, "(", round(100*pos_saliva/total_saliva,0), ")"))
note_mts <-  gsub(" ","",paste(pos_mts, "/", total_mts, "(", round(100*pos_mts/total_mts,0), ")")) 

    est <- signif(summary(model_day)$coefficients[2], digits = 2)
    se <- signif(summary(model_day)$coefficients[2,2], digits = 2)
    p <- signif(summary(model_day)$coefficients[2,4], digits = 2) 
    up <- est+1.96*se
    low <- est-1.96*se
    est_ci2 <- c(note, note_saliva, note_mts, est, low, up, p)
    return(est_ci2)
}
est_list_new <- rbind(table3(-3, 24),table3(-3, 2),table3(3,8),table3(9,24))
est_list_new
```



```{r}
#visualize  the effect of saliva on positivity over certain period
period_day <- function(day1, day2){
   #Create indicator "period_day": 1 if days_since_symptom_onset <=day, and 0 otherwise
  MT_SALIVA_POSITIVE_sub <- MT_SALIVA_POSITIVE_sub %>% 
  mutate(period_day = if_else(days_since_symptom_onset>=day1 & days_since_symptom_onset<=day2, 1, 0))

#subset those having results before day 
sub_day <- MT_SALIVA_POSITIVE_sub %>% 
  filter(period_day==1)

sub_day$sample_type <- factor(sub_day$sample_type,
                              levels = c("Midturbinate Swab", "Saliva"),
                              labels = c("MTS", "Saliva"))
sub_day$pos <- factor(sub_day$pos,
                      levels = c("TRUE", "FALSE"),
                      labels = c("Positive", "Negative"))


day.plot <- sub_day %>% 
  ggplot(aes(sample_type,..count.., fill=pos))+
  geom_bar(aes(fill=pos), position = "dodge")+
  labs (x="", y="", fill="Viral RNA detection")+
  geom_text(aes(label=..count..),stat='count',position=position_dodge(0.9), vjust = -0.3, size=3)+
  coord_cartesian(ylim = c(0,18))+
  theme_bw()
return(day.plot)
}

figure <- ggarrange (
period_day(-3, 2),
period_day(3, 8),
period_day(9, 24),
labels = c("A.  Day -3 through 2", 
           "B.  Day 3 through 8", 
           "C.  Day 9 through 24"),
ncol=3, nrow=1,
common.legend = T,
legend = "bottom",
font.label = list(size = 15),
hjust = -0.2,
vjust = 0.3)
figure_annotate <- annotate_figure(figure,
                 top = text_grob(""),
                 left = text_grob("Number of samples", rot=90))
ggsave(figure_annotate,filename="../output/figure_s2_samples_days_onset.png",device="png",width=11,height=7.77,units="in")
```

```{r}
exptransform <- function(x) {
  y <- exp(x) %>% signif(2)
  return(y)
}

df_new <- est_list_new %>% as.data.frame(stringsAsFactors=F)
colnames(df_new) <- c("varname","saliva","mts","beta","ci_low","ci_high", "p")
df_new$beta_1 <- df_new$beta %>% as.numeric() %>% sapply(exptransform)
df_new$ci_low_1 <- df_new$ci_low %>% as.numeric() %>% sapply(exptransform)
df_new$ci_high_1 <- df_new$ci_high %>% as.numeric() %>% sapply(exptransform)
df_new$predict1 <- df_new[,c("beta_1","ci_low_1","ci_high_1")] %>% apply(1,function(x) {paste0(x["beta_1"]," (",x["ci_low_1"],", ",x["ci_high_1"],")")})

table3_output_new <- df_new %>% select(varname,saliva, mts, predict1, p) %>% rename(`Days since symptom onset`=varname,
                                                                       `Positive Saliva (Sensitivity %)`=saliva,
                                                                       `Positive MTS (Sensitivity %)`=mts,
                                                                       `Odds Ratio Saliva:MTS`=predict1,
                                                                       `p-value`=p)
table3_output_new
write.csv(table3_output_new,file="../output/table_3a_rel_odds_onset.csv",row.names = F)
```

